name: "Ruby Gem"
description: "Power Home ruby gem build"
inputs:
  workdir:
    description: 'The working directory during this build'
    required: false
  ruby:
    description: 'The ruby version to use on this build'
    default: '3.3'
    required: false
  gemfile:
    description: 'The path to a Gemfile, relative to workdir'
    default: 'Gemfile'
    required: false
  bundler:
    description: 'Bundler major version'
    default: '2'
    required: false
runs:
  using: 'composite'
  steps:
    - name: 'Set up Ruby'
      uses: ruby/setup-ruby@v1
      env:
        BUNDLE_GEMFILE: '${{ inputs.gemfile }}'
        BUNDLER_VERSION: '${{ inputs.bundler }}'
        RAILS_ENV: 'test'
      with:
        bundler-cache: true
        bundler: '${{ inputs.bundler }}'
        ruby-version: '${{ inputs.ruby }}'
        working-directory: '${{ inputs.workdir }}'
    - name: 'Run the build script'
      env:
        BUNDLE_GEMFILE: '${{ inputs.gemfile }}'
        BUNDLER_VERSION: '${{ inputs.bundler }}'
        RAILS_ENV: 'test'
      working-directory: '${{ inputs.workdir }}'
      shell: 'bash'
      run: 'bundle exec rake'
