# Loads the whole dependency-delta stack. Individual files require only what they
# reference, so they can also be pulled in one at a time.
require_relative "dependency_delta/bundler_change_detector"
require_relative "dependency_delta/call_site_sample"
require_relative "dependency_delta/change"
require_relative "dependency_delta/change_detector"
require_relative "dependency_delta/changelog_source"
require_relative "dependency_delta/command"
require_relative "dependency_delta/generator"
require_relative "dependency_delta/git_locator"
require_relative "dependency_delta/git_snapshot"
require_relative "dependency_delta/playbook_kit_usage"
require_relative "dependency_delta/public_dependency_retriever"
require_relative "dependency_delta/public_downloader"
require_relative "dependency_delta/public_origin"
require_relative "dependency_delta/safe_tar_extractor"
require_relative "dependency_delta/source_diff"
require_relative "dependency_delta/source_diff_builder"
require_relative "dependency_delta/version_spelling"
require_relative "dependency_delta/yarn_change_detector"
require_relative "dependency_delta/yarn_lock_parser"
