on:
  workflow_call:
    inputs:
      workdir:
        required: false
        type: string
      decisions:
        required: false
        type: string
        default: doc/dependency_decisions.yml

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.2
          bundler-cache: true
          working-directory: ${{ inputs.workdir }}
      - run: gem install license_finder
      - name: Ensure license compliance with ${{ inputs.workdir }}/${{ inputs.decisions }}
        working-directory: ${{ inputs.workdir }}
        run: "license_finder --decisions-file=${{ inputs.decisions }}"
